### ISSUE TITLE
Assets that need to be made

### ISSUE THREAD

**Issue by AnonGuy** [CyberDiscovery/cyberdiscovery.github.io#3]
- [x] **Asset for the Survival Guide**
We've decided to stick with the official assets that were ~~stolen~~ liberated from the site.
- [x] **Asset for the CD App**
This could be a GIF of a phone view, with scrolling.
- [x] **Screenshot for the Maths bot**
- [x] **Screenshot for the General bot, with `:assess` functionality**

**Comment by Sh3llcod3** [comment]
Let's use a generic asset for now, the scrolling phone view is definitely something to consider later.
